### ISSUE TITLE
tauri-mock: run_advanced_query's groupBy branch never validates the cursor, so #3899's fix covers only the flat path

### ISSUE THREAD

**Issue by jfolcini** [jfolcini/agaric#3917]
Found in review of PR #3914 (which closes #3899 for the flat keyset path).

## The asymmetry

`run_advanced_query` (`src/lib/tauri-mock/handlers/search.ts`) returns early for a grouped request carrying any non-null cursor:

```ts
if (groupBy != null) {
  if (cursor != null) { return { rows: [], ... } }
  ...
}
```

`decodeCursor` is never reached. So after #3914, the flat path **throws** `validationRejection` on a malformed, foreign, or version-stale cursor — mirroring `QueryCursor::decode`'s four failure modes — while the grouped path silently accepts anything and returns an empty page.

That is the same divergence class #3899 was filed for, on the other arm of the same command.

## Why it was left, and why that is still worth tracking

Not a regression introduced by #3914: the grouped branch was already a stub. It does not implement grouped pagination at all — it returns a synthetic bucket / empty tail regardless of whether the cursor is valid, absent, or garbage. So there is no correct pagination behaviour there to diverge *from* yet.

Filing it rather than leaving it implied by #3914's `Closes #3899` line, because the closure would otherwise read as "malformed cursors are now rejected", which is true of one arm only.

## When this matters

Whenever grouped pagination is implemented for real. At that point the cursor becomes load-bearing on this path and the validation needs to land with it, not after it. Worth a test at that time pinning the same four failure modes the flat path now pins.

## Suggested approach

When grouped pagination is implemented, route its cursor through the same `decodeCursor` and let it throw. Until then this is a documentation-and-tracking item — the early return could carry a comment naming this issue so the next person to touch it sees the obligation.
