### ISSUE TITLE
ci: pr-merge-result-check runs only the ratchet guards, so a semantic merge collision in ordinary source passes it

### ISSUE THREAD

**Issue by jfolcini** [jfolcini/agaric#4078]
`pr-merge-result-check` exists for the "#3724 shape": each branch is correct alone, the merge is wrong, and git reports no conflict so nothing stops it. It computes the merge result and runs the ratchet guards against it.

**It runs only the guards.** No `tsc`, no vitest, no cargo. So the same failure class in ordinary source code passes it completely.

## It happened tonight, and only the release build caught it

#4074 and #4075 were both green on their own branches and merged within minutes of each other. Their merge does not typecheck:

```
markdown-roundtrip.property.test.ts(860,42): error TS2304: Cannot find name 'NESTING_SEED'.
markdown-roundtrip.property.test.ts(916,17): error TS2304: Cannot find name 'hasKnownIssue4049Drift'.
```

#4074 consolidated the property seeds and deleted `hasKnownIssue4049Drift`; #4075 added three properties still referencing both. Disjoint hunks in one file — **no textual conflict**, so git merged them silently and both PR CI runs were green because each branch was internally consistent.

`main` sat un-compilable until a release-build verification failed on it (#4077). Nothing else would have reported it until the next PR's CI ran against the new `main` — at which point the failure would have looked like *that* PR's fault.

## Why the existing checks did not help

- **`pr-merge-result-check`** — guards only, as above.
- **The `overlap` job** — both PRs touched `markdown-roundtrip.property.test.ts`, so an overlap warning is the natural place for this, but it did not block. Worth checking whether it fired at all and, if so, whether a same-file overlap between two open PRs should be advisory or blocking.
- **Per-PR CI** — structurally cannot see it. It tests the branch, not the branch merged into whatever `main` has become since.

## Suggested direction

Extend the merge-result check beyond the guards to at least `tsc -b --noEmit`, which is fast, deterministic, and catches exactly this class. The full vitest/cargo suites are probably too slow for every PR, but a typecheck of the merge result is cheap.

Whatever the mechanism, the acceptance is falsification-shaped and easy to build from this incident: construct two branches that each typecheck alone and whose merge does not — one deleting an export, the other adding a reference to it — and assert the check exits non-zero. Demonstrate it RED against the current script first, since today it exits 0 on precisely that input.

## Related

- #4077 — the hotfix, with the full diagnosis.
- #4076 — two pre-existing convergence bugs the repair surfaced.

**Comment by jfolcini** [comment]
Claimed — working on this in a Claude session.
